## Project 1 - Data Cleaning
### Team 5 - Subhav & Preet

Data
The data comes from two different sources:

The NYC crime data describes all valid felony, misdemeanor, and violation crimes reported to the New York City Police Department (NYPD) from 2006 to the end of last year (2019). Each instance has a record of the date, time, location, crime details, suspect details and any other relevant information that the NYPD uses. This data is spread in one table of 35 columns and 7375993 rows.
Data link: https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i/data


Data Cleaning: The data itself is in a clean format. We need to drop some of the columns, change column names, remove whitespaces from certain columns, adjust the data types, and add a few columns like report_year and report_month.

The Airbnb listing data describes all the information about a particular listing including date of listing, location, amenities, neighborhood, transit, rental size, listing score, and much more from 2008 to 2019. This information comes from the following article: https://medium.com/@lilyng15/data-analysis-on-airbnb-new-york-city-60bb85560a01 and that redirected us to the following git repository: https://github.com/ioslilyng/airbnb_nyc/tree/master/data This data is spread in one table of 81 columns and 49531 rows.
Data link: https://github.com/ioslilyng/airbnb_nyc/tree/master/data


Data Cleaning: The data itself is in a clean format. We need to drop some of the columns, change column names, remove whitespaces or $ symbols from certain columns and adjust the data types
As far as the datasets being used are concerned, yes, they have been used to analyze and gain insights into NYC gun crimes and to analyze and gain insights into NYC Airbnb listings separately (Links below). Our problem domain is quite different from the ones above.
NYC Shooting EDA: https://www.linkedin.com/pulse/new-york-shooting-2006-2019-exploratory-data-analysis-magdy/
NYC Airbnb listings: https://medium.com/@lilyng15/data-analysis-on-airbnb-new-york-city-60bb85560a01

### Importing the relevant libraries

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### Mounting Google Drive folder to accesss datasets

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

### Reading the Airbnb listings dataset

In [ ]:
data_airbnb = pd.read_csv('/content/drive/My Drive/Team-5_95885/Project1/Project_Deliverables/Final/Datasets/Airbnb_listings.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (43,61,62,94,95) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
data_airbnb.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2060,https://www.airbnb.com/rooms/2060,20200608144437,2020-06-09,Modern NYC,NaN,"Lovely, spacious, sunny 1 BR apartment in 6th ...","Lovely, spacious, sunny 1 BR apartment in 6th ...",none,NaN,...,f,f,flexible,f,f,1,0,1,0,0.01
1,2595,https://www.airbnb.com/rooms/2595,20200608144437,2020-06-09,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...","- Spacious (500+ftÂ²), immaculate and nicely fu...","Beautiful, spacious skylit studio in the heart...",none,Centrally located in the heart of Manhattan ju...,...,f,f,strict_14_with_grace_period,t,t,2,2,0,0,0.37
2,3831,https://www.airbnb.com/rooms/3831,20200608144437,2020-06-09,"Whole flr w/private bdrm, bath & kitchen(pls r...","Enjoy 500 s.f. top floor in 1899 brownstone, w...",We host on the entire top floor of our double-...,"Enjoy 500 s.f. top floor in 1899 brownstone, w...",none,Just the right mix of urban center and local n...,...,f,f,flexible,f,f,1,1,0,0,4.64
3,5099,https://www.airbnb.com/rooms/5099,20200608144437,2020-06-09,Large Cozy 1 BR Apartment In Midtown East,My large 1 bedroom apartment has a true New Yo...,I have a large 1 bedroom apartment centrally l...,My large 1 bedroom apartment has a true New Yo...,none,My neighborhood in Midtown East is called Murr...,...,f,f,moderate,t,t,1,1,0,0,0.58
4,5121,https://www.airbnb.com/rooms/5121,20200608144437,2020-06-09,BlissArtsSpace!,NaN,HELLO EVERYONE AND THANKS FOR VISITING BLISS A...,HELLO EVERYONE AND THANKS FOR VISITING BLISS A...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,1,0,1,0,0.37

### Cleaning the Airbnb listings dataframe

In [ ]:
# Dropping the columns which are not required
data_airbnb = data_airbnb.drop(columns = 'listing_url   scrape_id last_scraped name summary space \
                        experiences_offered neighborhood_overview  notes  transit \
                        access interaction house_rules thumbnail_url medium_url picture_url \
                        xl_picture_url host_neighbourhood host_url host_listings_count host_name \
                        host_location host_about host_response_time \
                        host_response_rate host_acceptance_rate host_is_superhost host_thumbnail_url \
                        host_picture_url host_verifications host_has_profile_pic host_identity_verified \
                        street neighbourhood city state zipcode market \
                        smart_location country_code country is_location_exact accommodates \
                        bathrooms beds bedrooms bed_type amenities square_feet weekly_price \
                        monthly_price security_deposit cleaning_fee guests_included extra_people  \
                        minimum_nights maximum_nights minimum_minimum_nights maximum_minimum_nights \
                        minimum_maximum_nights maximum_maximum_nights minimum_nights_avg_ntm \
                        maximum_nights_avg_ntm calendar_updated has_availability availability_30 \
                        availability_60 availability_90 availability_365 calendar_last_scraped \
                        number_of_reviews_ltm first_review last_review review_scores_cleanliness \
                        review_scores_checkin review_scores_communication requires_license \
                        license jurisdiction_names instant_bookable is_business_travel_ready \
                        cancellation_policy require_guest_profile_picture \
                        require_guest_phone_verification calculated_host_listings_count \
                        calculated_host_listings_count_entire_homes \
                        calculated_host_listings_count_private_rooms \
                        calculated_host_listings_count_shared_rooms reviews_per_month'.split())

In [ ]:
# Renaming the columns
data_airbnb.rename(columns={'id':'bnb_id', 'host_total_listings_count':'listing_count', 
                    'neighbourhood_cleansed':'neighbourhood',
                    'neighbourhood_group_cleansed':'borough', 'number_of_reviews':'reviews',
                    'review_scores_rating':'rating', 'review_scores_accuracy':'accuracy_score',
                     'review_scores_location':'location_score', 'review_scores_value':'value_score'},
           inplace = True)

In [ ]:
# Cleaning the columns
data_airbnb.price = data_airbnb.price.apply(lambda x: ((x.lstrip('$'))))
data_airbnb.price = data_airbnb.price.replace(',','', regex=True )

In [ ]:
# Adjusting the data types
data_airbnb.price = data_airbnb.price.astype('float')
data_airbnb['host_since'] = pd.to_datetime(data_airbnb['host_since'])
data_airbnb = data_airbnb[data_airbnb['host_since'].notna()]
data_airbnb['host_since_year'] = pd.DatetimeIndex(data_airbnb['host_since']).year.astype(int)
data_airbnb.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

bnb_id                      int64
description                object
host_id                     int64
host_since         datetime64[ns]
listing_count             float64
neighbourhood              object
borough                    object
latitude                  float64
longitude                 float64
property_type              object
room_type                  object
price                     float64
reviews                     int64
rating                    float64
accuracy_score            float64
location_score            float64
value_score               float64
host_since_year             int64
dtype: object

In [ ]:
data_airbnb.isna().sum()

bnb_id                  0
description          1290
host_id                 0
host_since              0
listing_count           0
neighbourhood           0
borough                 0
latitude                0
longitude               0
property_type           0
room_type               0
price                   0
reviews                 0
rating              12283
accuracy_score      12317
location_score      12333
value_score         12332
host_since_year         0
latitude_impute         0
longitude_impute        0
dtype: int64

While about 25% of the listings data does not have a rating, accuracy_score, location_score, value_score values, none of the listings are irrelevant because the values exist for the most relevant columns. When the columns with nan values are being looked at, these rows will be imputed with the average values for airbnb's based on their respective neighborhood and the listing size. An interesting thing to see here would be which neighbourhood is most commonly missing a rating.

As for the description column, only about 2.5% of the rows have nan values and might be deleted during the respective analysis if needed.

### Saving the cleaned Airbnb listings file

In [ ]:
data_airbnb.to_csv('/content/drive/My Drive/Team-5_95885/Project1/Project_Deliverables/Final/Datasets/cleaned_airbnb_listings.csv',index=False)

### Reading the NYC Crimes dataset

In [ ]:
df_crimes = pd.read_csv('/content/drive/My Drive/Team-5_95885/Project1/Project_Deliverables/Final/Datasets/NYPD_Complaint_Data_Historic.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (18,20) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
df_crimes.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,...,SUSP_SEX,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,394506329,12/31/2019,17:30:00,NaN,NaN,32.0,12/31/2019,118,DANGEROUS WEAPONS,793.0,...,NaN,NaN,40.820927,-73.943324,"(40.82092679700002, -73.94332421899996)",PATROL BORO MAN NORTH,NaN,UNKNOWN,UNKNOWN,E
1,968873685,12/29/2019,16:31:00,12/29/2019,16:54:00,47.0,12/29/2019,113,FORGERY,729.0,...,NaN,NaN,40.885701,-73.861640,"(40.885701406000074, -73.86164032499995)",PATROL BORO BRONX,NaN,UNKNOWN,UNKNOWN,E
2,509837549,12/15/2019,18:45:00,NaN,NaN,109.0,12/29/2019,578,HARRASSMENT 2,638.0,...,M,NaN,40.742281,-73.819824,"(40.74228115600005, -73.81982408)",PATROL BORO QUEENS NORTH,NaN,25-44,WHITE HISPANIC,F
3,352454313,12/28/2019,01:00:00,NaN,NaN,47.0,12/28/2019,126,MISCELLANEOUS PENAL LAW,117.0,...,M,NaN,40.875311,-73.847545,"(40.87531145100007, -73.84754521099995)",PATROL BORO BRONX,NaN,UNKNOWN,UNKNOWN,E
4,248803469,09/05/2008,21:41:00,NaN,NaN,NaN,09/05/2008,101,MURDER & NON-NEGL. MANSLAUGHTER,NaN,...,NaN,NaN,40.698827,-73.938819,"(40.698827283, -73.938819047)",NaN,NaN,25-44,BLACK,M

### Cleaning the crimes dataframe

In [ ]:
# Drop the columns not needed
df_crimes = df_crimes.drop(columns=['CMPLNT_FR_TM', 'CMPLNT_TO_DT', 'CMPLNT_TO_TM','ADDR_PCT_CD', 
                      'PD_CD','PD_DESC', 'CRM_ATPT_CPTD_CD','LOC_OF_OCCUR_DESC', 
                      'PREM_TYP_DESC', 'JURIS_DESC', 'JURISDICTION_CODE',
                      'PARKS_NM', 'HADEVELOPT', 'HOUSING_PSA','X_COORD_CD', 
                      'Y_COORD_CD','TRANSIT_DISTRICT', 'STATION_NAME'])

In [ ]:
#Renaming the columns
df_crimes.rename(columns={'CMPLNT_NUM': 'complaint_num', 'CMPLNT_FR_DT': 'crime_date',
                   'RPT_DT': 'report_date', 'LAW_CAT_CD': 'law_cat',
                   'KY_CD': 'offense_code', 'OFNS_DESC': 'offense_desc',
                   'BORO_NM': 'borough', 'OFNS_DESC': 'offense_desc',
                   'SUSP_AGE_GROUP': 'susp_age_gp', 'SUSP_RACE': 'susp_race',
                   'SUSP_SEX': 'susp_sex', 'VIC_AGE_GROUP': 'vic_age_gp',
                   'Latitude': 'latitude', 'Longitude': 'longitude',
                   'Lat_Lon': 'lat_lon','VIC_SEX': 'vic_sex', 'VIC_RACE': 'vic_race', 'PATROL_BORO': 'patrol_boro'},
          inplace=True)

In [ ]:
#Changeing the crime_date and report_date to datetime objects
df_crimes['crime_date']= pd.to_datetime(df_crimes['crime_date'], errors = 'coerce')
df_crimes['report_date']= pd.to_datetime(df_crimes['report_date'], errors = 'coerce')

In [ ]:
#Stripping off the whitespaces from all the string rows
df_crimes = df_crimes.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [ ]:
# Adding the report_year and report_month columns
df_crimes['report_year'] = pd.DatetimeIndex(df_crimes['report_date']).year
df_crimes['report_month'] = pd.DatetimeIndex(df_crimes['report_date']).month
df_crimes.head()

,complaint_num,crime_date,report_date,offense_code,offense_desc,law_cat,borough,susp_age_gp,susp_race,susp_sex,latitude,longitude,lat_lon,patrol_boro,vic_age_gp,vic_race,vic_sex,report_year,report_month
0,394506329,2019-12-31,2019-12-31,118,DANGEROUS WEAPONS,FELONY,MANHATTAN,NaN,NaN,NaN,40.820927,-73.943324,"(40.82092679700002, -73.94332421899996)",PATROL BORO MAN NORTH,UNKNOWN,UNKNOWN,E,2019,12
1,968873685,2019-12-29,2019-12-29,113,FORGERY,FELONY,BRONX,NaN,NaN,NaN,40.885701,-73.861640,"(40.885701406000074, -73.86164032499995)",PATROL BORO BRONX,UNKNOWN,UNKNOWN,E,2019,12
2,509837549,2019-12-15,2019-12-29,578,HARRASSMENT 2,VIOLATION,QUEENS,25-44,UNKNOWN,M,40.742281,-73.819824,"(40.74228115600005, -73.81982408)",PATROL BORO QUEENS NORTH,25-44,WHITE HISPANIC,F,2019,12
3,352454313,2019-12-28,2019-12-28,126,MISCELLANEOUS PENAL LAW,FELONY,BRONX,18-24,BLACK,M,40.875311,-73.847545,"(40.87531145100007, -73.84754521099995)",PATROL BORO BRONX,UNKNOWN,UNKNOWN,E,2019,12
4,248803469,2008-09-05,2008-09-05,101,MURDER & NON-NEGL. MANSLAUGHTER,FELONY,NaN,NaN,NaN,NaN,40.698827,-73.938819,"(40.698827283, -73.938819047)",NaN,25-44,BLACK,M,2008,9

### Saving the cleaned NYC Crimes file

In [ ]:
df_crimes.to_csv('/content/drive/My Drive/Team-5_95885/Project1/Project_Deliverables/Final/Datasets/cleaned_nyc_crimes.csv',index=False)